[package]
name = "climberld50"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gl = "0.14.0"
png = "0.17.5"
sdl2 = { version = "0.35.2", features = ["bundled", "static-link"] }
rand = "0.8.5"